/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Avro Schema for our Customer */
@org.apache.avro.specific.AvroGenerated
public class CustomerV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 288835714236606465L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerV2\",\"namespace\":\"com.example\",\"doc\":\"Avro Schema for our Customer\",\"fields\":[{\"name\":\"first_name\",\"type\":\"string\",\"doc\":\"First Name of Customer\"},{\"name\":\"age1\",\"type\":\"int\",\"doc\":\"Age at the time of registration\",\"default\":0},{\"name\":\"height\",\"type\":\"float\",\"doc\":\"Height at the time of registration in cm\",\"default\":0.0},{\"name\":\"phone\",\"type\":[\"null\",\"string\"],\"doc\":\"Age at the time of registration\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerV2> ENCODER =
      new BinaryMessageEncoder<CustomerV2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerV2> DECODER =
      new BinaryMessageDecoder<CustomerV2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerV2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerV2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerV2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerV2>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerV2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerV2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerV2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerV2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** First Name of Customer */
  private java.lang.CharSequence first_name;
  /** Age at the time of registration */
  private int age1;
  /** Height at the time of registration in cm */
  private float height;
  /** Age at the time of registration */
  private java.lang.CharSequence phone;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerV2() {}

  /**
   * All-args constructor.
   * @param first_name First Name of Customer
   * @param age1 Age at the time of registration
   * @param height Height at the time of registration in cm
   * @param phone Age at the time of registration
   */
  public CustomerV2(java.lang.CharSequence first_name, java.lang.Integer age1, java.lang.Float height, java.lang.CharSequence phone) {
    this.first_name = first_name;
    this.age1 = age1;
    this.height = height;
    this.phone = phone;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first_name;
    case 1: return age1;
    case 2: return height;
    case 3: return phone;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first_name = (java.lang.CharSequence)value$; break;
    case 1: age1 = (java.lang.Integer)value$; break;
    case 2: height = (java.lang.Float)value$; break;
    case 3: phone = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return First Name of Customer
   */
  public java.lang.CharSequence getFirstName() {
    return first_name;
  }


  /**
   * Sets the value of the 'first_name' field.
   * First Name of Customer
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'age1' field.
   * @return Age at the time of registration
   */
  public int getAge1() {
    return age1;
  }


  /**
   * Sets the value of the 'age1' field.
   * Age at the time of registration
   * @param value the value to set.
   */
  public void setAge1(int value) {
    this.age1 = value;
  }

  /**
   * Gets the value of the 'height' field.
   * @return Height at the time of registration in cm
   */
  public float getHeight() {
    return height;
  }


  /**
   * Sets the value of the 'height' field.
   * Height at the time of registration in cm
   * @param value the value to set.
   */
  public void setHeight(float value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'phone' field.
   * @return Age at the time of registration
   */
  public java.lang.CharSequence getPhone() {
    return phone;
  }


  /**
   * Sets the value of the 'phone' field.
   * Age at the time of registration
   * @param value the value to set.
   */
  public void setPhone(java.lang.CharSequence value) {
    this.phone = value;
  }

  /**
   * Creates a new CustomerV2 RecordBuilder.
   * @return A new CustomerV2 RecordBuilder
   */
  public static com.example.CustomerV2.Builder newBuilder() {
    return new com.example.CustomerV2.Builder();
  }

  /**
   * Creates a new CustomerV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerV2 RecordBuilder
   */
  public static com.example.CustomerV2.Builder newBuilder(com.example.CustomerV2.Builder other) {
    if (other == null) {
      return new com.example.CustomerV2.Builder();
    } else {
      return new com.example.CustomerV2.Builder(other);
    }
  }

  /**
   * Creates a new CustomerV2 RecordBuilder by copying an existing CustomerV2 instance.
   * @param other The existing instance to copy.
   * @return A new CustomerV2 RecordBuilder
   */
  public static com.example.CustomerV2.Builder newBuilder(com.example.CustomerV2 other) {
    if (other == null) {
      return new com.example.CustomerV2.Builder();
    } else {
      return new com.example.CustomerV2.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerV2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerV2>
    implements org.apache.avro.data.RecordBuilder<CustomerV2> {

    /** First Name of Customer */
    private java.lang.CharSequence first_name;
    /** Age at the time of registration */
    private int age1;
    /** Height at the time of registration in cm */
    private float height;
    /** Age at the time of registration */
    private java.lang.CharSequence phone;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.CustomerV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.age1)) {
        this.age1 = data().deepCopy(fields()[1].schema(), other.age1);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.height)) {
        this.height = data().deepCopy(fields()[2].schema(), other.height);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.CustomerV2 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age1)) {
        this.age1 = data().deepCopy(fields()[1].schema(), other.age1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.height)) {
        this.height = data().deepCopy(fields()[2].schema(), other.height);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone)) {
        this.phone = data().deepCopy(fields()[3].schema(), other.phone);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'first_name' field.
      * First Name of Customer
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return first_name;
    }


    /**
      * Sets the value of the 'first_name' field.
      * First Name of Customer
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public com.example.CustomerV2.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.first_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * First Name of Customer
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first_name' field.
      * First Name of Customer
      * @return This builder.
      */
    public com.example.CustomerV2.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age1' field.
      * Age at the time of registration
      * @return The value.
      */
    public int getAge1() {
      return age1;
    }


    /**
      * Sets the value of the 'age1' field.
      * Age at the time of registration
      * @param value The value of 'age1'.
      * @return This builder.
      */
    public com.example.CustomerV2.Builder setAge1(int value) {
      validate(fields()[1], value);
      this.age1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age1' field has been set.
      * Age at the time of registration
      * @return True if the 'age1' field has been set, false otherwise.
      */
    public boolean hasAge1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age1' field.
      * Age at the time of registration
      * @return This builder.
      */
    public com.example.CustomerV2.Builder clearAge1() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * Height at the time of registration in cm
      * @return The value.
      */
    public float getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * Height at the time of registration in cm
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.example.CustomerV2.Builder setHeight(float value) {
      validate(fields()[2], value);
      this.height = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * Height at the time of registration in cm
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'height' field.
      * Height at the time of registration in cm
      * @return This builder.
      */
    public com.example.CustomerV2.Builder clearHeight() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone' field.
      * Age at the time of registration
      * @return The value.
      */
    public java.lang.CharSequence getPhone() {
      return phone;
    }


    /**
      * Sets the value of the 'phone' field.
      * Age at the time of registration
      * @param value The value of 'phone'.
      * @return This builder.
      */
    public com.example.CustomerV2.Builder setPhone(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.phone = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'phone' field has been set.
      * Age at the time of registration
      * @return True if the 'phone' field has been set, false otherwise.
      */
    public boolean hasPhone() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'phone' field.
      * Age at the time of registration
      * @return This builder.
      */
    public com.example.CustomerV2.Builder clearPhone() {
      phone = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerV2 build() {
      try {
        CustomerV2 record = new CustomerV2();
        record.first_name = fieldSetFlags()[0] ? this.first_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.age1 = fieldSetFlags()[1] ? this.age1 : (java.lang.Integer) defaultValue(fields()[1]);
        record.height = fieldSetFlags()[2] ? this.height : (java.lang.Float) defaultValue(fields()[2]);
        record.phone = fieldSetFlags()[3] ? this.phone : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerV2>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerV2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerV2>
    READER$ = (org.apache.avro.io.DatumReader<CustomerV2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.first_name);

    out.writeInt(this.age1);

    out.writeFloat(this.height);

    if (this.phone == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.phone);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.first_name = in.readString(this.first_name instanceof Utf8 ? (Utf8)this.first_name : null);

      this.age1 = in.readInt();

      this.height = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.phone = null;
      } else {
        this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.first_name = in.readString(this.first_name instanceof Utf8 ? (Utf8)this.first_name : null);
          break;

        case 1:
          this.age1 = in.readInt();
          break;

        case 2:
          this.height = in.readFloat();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.phone = null;
          } else {
            this.phone = in.readString(this.phone instanceof Utf8 ? (Utf8)this.phone : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










